#!/usr/bin/env python3
"""Generate the Claywork gallery from the images in Images/Claywork, and point
the home-page Claywork teaser at the first (most important) image.

Images are ordered by filename, so a numeric prefix sets priority:
    1_xxx.jpeg, 2_xxx.jpeg, 3_xxx.jpeg, then the rest alphabetically.
The first image is used top-left on the Claywork page AND as the home teaser.
No captions are added.

Run after adding/removing photos:
    python3 build_claywork.py
"""
import re, html, json, pathlib

ROOT = pathlib.Path(__file__).parent
IMG_DIR = ROOT / "Images" / "Claywork"
CLAYWORK = ROOT / "claywork.html"
INDEX = ROOT / "index.html"
EXTS = {".jpg", ".jpeg", ".png", ".webp", ".gif"}
ALT = "Wheel-thrown ceramic piece by Hamish Patten"
BASE = "https://hamishwp.github.io/mywebsite/"

def images():
    files = [p for p in IMG_DIR.iterdir() if p.suffix.lower() in EXTS]
    files.sort(key=lambda p: p.name)           # numeric prefixes (1_,2_,3_) come first
    return [f"Images/Claywork/{p.name}" for p in files]

def gallery_html(paths):
    figs = "\n".join(
        f'      <figure><img src="{src}" alt="{html.escape(ALT)}" loading="lazy"></figure>'
        for src in paths)
    return f'    <div class="gallery">\n{figs}\n    </div>'

def jsonld_gallery(paths):
    data = {
        "@context": "https://schema.org",
        "@type": "ImageGallery",
        "name": "Claywork — Hamish Patten",
        "url": BASE + "claywork.html",
        "about": "Wheel-thrown ceramics by Hamish Patten",
        "image": [BASE + p for p in paths],
    }
    return ('  <script type="application/ld+json">\n  '
            + json.dumps(data, ensure_ascii=False, indent=2).replace("\n", "\n  ")
            + "\n  </script>")

def splice(text, start, end, replacement):
    pattern = re.compile(re.escape(start) + r".*?" + re.escape(end), re.DOTALL)
    block = f"{start}\n{replacement}\n    {end}"
    if not pattern.search(text):
        raise SystemExit(f"Markers {start} ... {end} not found.")
    return pattern.sub(lambda m: block, text, count=1)

def update_home_teaser(first):
    text = INDEX.read_text(encoding="utf-8")
    # Replace the image span inside the Claywork teaser (handles placeholder or existing img).
    pat = re.compile(
        r'(<a class="teaser" href="claywork\.html">\s*)<span class="teaser-img[^"]*">.*?</span>',
        re.DOTALL)
    new_span = f'<span class="teaser-img"><img src="{first}" alt="{html.escape(ALT)}"></span>'
    if not pat.search(text):
        print("  ! Claywork teaser not found in index.html — skipped home update.")
        return
    INDEX.write_text(pat.sub(lambda m: m.group(1) + new_span, text, count=1), encoding="utf-8")
    print(f"  Home teaser image -> {first}")

def main():
    paths = images()
    if not paths:
        raise SystemExit("No images found in Images/Claywork.")
    start = "<!-- GALLERY:START — generated by build_claywork.py; edit photos in Images/Claywork and re-run -->"
    end = "<!-- GALLERY:END -->"
    text = CLAYWORK.read_text(encoding="utf-8")
    text = splice(text, start, end, gallery_html(paths))
    text = splice(text, "<!-- JSONLD:START -->", "<!-- JSONLD:END -->", jsonld_gallery(paths))
    CLAYWORK.write_text(text, encoding="utf-8")
    print(f"Claywork gallery: {len(paths)} images (first = {paths[0].split('/')[-1]})")
    update_home_teaser(paths[0])

if __name__ == "__main__":
    main()
